<h3> 1) 주어진 데이터(‘assignment1_data.xlsx’) 불러오기 및 numpy array화 </h3>

In [55]:
import numpy as np
import pandas as pd

In [56]:
data = pd.read_excel('assignment1_data.xlsx')

In [57]:
data.head()

num_viewers       title  running_time  netizen_ratings  num_reviews  \
0        94993  소년은 울지 않는다            98             5.62          266   
1      1240953       꿀벌대소동            88             8.09         1291   
2       431376   마법에 걸린 사랑           106             8.99         3105   
3       590409   뜨거운 것이 좋아           114             6.84         3198   
4       422363     기다리다 미쳐           108             7.37         1547   

   num_article  released_year  released_month  country_others  country_USA  \
0          352           2008              11               0            0   
1            0           2008               1               0            1   
2           17           2008               1               0            1   
3          997           2008               1               0            0   
4          225           2008               1               0            0   

   ...  genre_SF  genre_Horror  genre_Drama  genre_Romance  genre_Thriller  \
0  ...         0             0            0              0               0   
1  ...         0             0            0              0               0   
2  ...         0             0            0              1               0   
3  ...         0             0            1              0               0   
4  ...         0             0            0              1               0   

   genre_Ani  genre_Action  genre_Adventure  genre_Comedy  genre_others  
0          0             1                0             0             0  
1          0             0                0             0             1  
2          0             0                0             0             0  
3          0             0                0             0             0  
4          0             0                0             0             0  

[5 rows x 26 columns]

In [58]:
data_np = data.values

<h3> 2) 종속변수(‘num_viewers’) 및 독립변수(feature) 구분 </h3>

In [59]:
y = data_np[:,0]
X = data_np[:,2:] # 독립변수(feature) 반영 정도에 따른 모형 예측력은 하단 코드 참조

<h3> 3) train_test_split 함수를 이용하여 7:3 비율로 학습/평가 데이터 구분 </h3>

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3) # 8:2, 6:4 비율 설정에 따른 모형 예측력은 하단 코드 참조

In [61]:
X_train.shape

(984, 24)

In [62]:
y_train.shape

(984,)

<h3> 4) LinearRegression() 생성자 함수로 객체(‘model’ 등) 생성 후 학습 데이터에 적합 </h3>

In [63]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [64]:
model1 = LinearRegression(fit_intercept = False)
model1.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [65]:
# Feature Scaling 1 / Standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [66]:
X_train_std = scaler.fit_transform(X_train) # 독립변수만 scaling
X_test_std = scaler.transform(X_test) # 독립변수만 scaling

In [67]:
model_std = LinearRegression()
model_std.fit(X_train_std, y_train)

LinearRegression()

In [68]:
# Standardization, fit_intercept = False
model_std1 = LinearRegression(fit_intercept = False)
model_std1.fit(X_train_std, y_train)

LinearRegression(fit_intercept=False)

In [69]:
# Feature Scaling 2 / Min-max scaling

from sklearn.preprocessing import MinMaxScaler
scaler_minmax = MinMaxScaler()

In [70]:
X_train_minmax = scaler_minmax.fit_transform(X_train)
X_test_minmax = scaler_minmax.transform(X_test)

In [71]:
model_minmax = LinearRegression()
model_minmax.fit(X_train_minmax, y_train)

LinearRegression()

In [72]:
# Min-max scaling, fit_intercept = False

model_minmax1 = LinearRegression(fit_intercept = False)
model_minmax1.fit(X_train_minmax, y_train)

LinearRegression(fit_intercept=False)

In [73]:
# Cross-validation
# validation folds에 따른 모형 예측력은 하단 코드 참조

from sklearn.model_selection import cross_val_score

In [74]:
scores = cross_val_score(model, X_train, y_train, cv=5)
print(scores.mean())
scores1 = cross_val_score(model1, X_train, y_train, cv=5)
print(scores1.mean())
scores_std = cross_val_score(model_std, X_train_std, y_train, cv=5)
print(scores_std.mean())
scores_std1 = cross_val_score(model_std1, X_train_std, y_train, cv=5)
print(scores_std1.mean())
scores_minmax = cross_val_score(model_minmax, X_train_minmax, y_train, cv=5)
print(scores_minmax.mean())
scores_minmax1 = cross_val_score(model_minmax1, X_train_minmax, y_train, cv=5)
print(scores_minmax1.mean())

0.7401615873641952
0.7401615873642048
0.7396854047467084
0.365497215251456
0.7401336776950262
0.7401615873641982


<h3> 5) 평가 데이터에 적용하여 예측력(R^2,  결정계수) 계산 </h3>

In [88]:
model_minmax1.score(X_test_minmax, y_test)

0.7133122527209199

<h3> 참조: 학습/평가 데이터 비율 및 독립변수(feature), validation folds 수 선정 </h3>

In [76]:
y_tmp = data_np[:,0]

model_featureselection = LinearRegression()
for i in range(1,26) :
        X_tmp = data_np[:,2:i+2]
        model_featureselection.fit(X_tmp, y_tmp)
        print(str(i)+"번째 모형의 결정계수 : "+ str(model_featureselection.score(X_tmp, y_tmp)))

1번째 모형의 결정계수 : 0.09743997714385344
2번째 모형의 결정계수 : 0.12378689945591226
3번째 모형의 결정계수 : 0.7146579938799095
4번째 모형의 결정계수 : 0.7259954787835139
5번째 모형의 결정계수 : 0.7315344307615185
6번째 모형의 결정계수 : 0.7315347304968903
7번째 모형의 결정계수 : 0.7327309908544117
8번째 모형의 결정계수 : 0.7371084185155652
9번째 모형의 결정계수 : 0.7371101091305661
10번째 모형의 결정계수 : 0.737110109130566
11번째 모형의 결정계수 : 0.7371783802490208
12번째 모형의 결정계수 : 0.737223925494453
13번째 모형의 결정계수 : 0.7430336816296539
14번째 모형의 결정계수 : 0.7430336816296539
15번째 모형의 결정계수 : 0.7431769804016436
16번째 모형의 결정계수 : 0.7431956110725619
17번째 모형의 결정계수 : 0.7478091497686088
18번째 모형의 결정계수 : 0.7502972821832968
19번째 모형의 결정계수 : 0.7506143399130412
20번째 모형의 결정계수 : 0.7508139595440075
21번째 모형의 결정계수 : 0.7529533826874679
22번째 모형의 결정계수 : 0.7530061349632753
23번째 모형의 결정계수 : 0.75300613499234
24번째 모형의 결정계수 : 0.75300613499234
25번째 모형의 결정계수 : 0.75300613499234


In [77]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.2)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.4)

# 학습/평가 데이터 8:2 비율 모형 적합 및 feature scaling

model_1 = LinearRegression()
model1_1 = LinearRegression(fit_intercept = False)
model_1.fit(X_train1, y_train1)
model1_1.fit(X_train1, y_train1)

X_train1_std = scaler.fit_transform(X_train1) # 독립변수만 scaling
X_test1_std = scaler.transform(X_test1) # 독립변수만 scaling

model_1_std = LinearRegression()
model_1_std1 = LinearRegression(fit_intercept = False)
model_1_std.fit(X_train1_std, y_train1)
model_1_std1.fit(X_train1_std, y_train1)

X_train1_minmax = scaler_minmax.fit_transform(X_train1)
X_test1_minmax = scaler_minmax.transform(X_test1)

model_1_minmax = LinearRegression()
model_1_minmax1 = LinearRegression(fit_intercept = False)
model_1_minmax.fit(X_train1_minmax, y_train1)
model_1_minmax1.fit(X_train1_minmax, y_train1)

# 학습/평가 데이터 6:4 비율 모형 적합 및 feature scaling

model_2 = LinearRegression()
model1_2 = LinearRegression(fit_intercept = False)
model_2.fit(X_train2, y_train2)
model1_2.fit(X_train2, y_train2)

X_train2_std = scaler.fit_transform(X_train2) # 독립변수만 scaling
X_test2_std = scaler.transform(X_test2) # 독립변수만 scaling

model_2_std = LinearRegression()
model_2_std1 = LinearRegression(fit_intercept = False)
model_2_std.fit(X_train2_std, y_train2)
model_2_std1.fit(X_train2_std, y_train2)

X_train2_minmax = scaler_minmax.fit_transform(X_train2)
X_test2_minmax = scaler_minmax.transform(X_test2)

model_2_minmax = LinearRegression()
model_2_minmax1 =LinearRegression(fit_intercept = False)
model_2_minmax.fit(X_train2_minmax, y_train2)
model_2_minmax1.fit(X_train2_minmax, y_train2)

LinearRegression(fit_intercept=False)

In [78]:
# 학습/평가 데이터 8:2 비율 모형 cross-validation 시행 후 예측력 계산

scores11 = cross_val_score(model_1, X_train1, y_train1, cv=5)
print("feature scaling 미시행 및 fit_intercept=True : "+str(scores11.mean()))
scores12 = cross_val_score(model1_1, X_train1, y_train1, cv=5)
print("feature scaling 미시행 및 fit_intercept=False : "+str(scores12.mean()))
scores13 = cross_val_score(model_1_std, X_train1_std, y_train1, cv=5)
print("Standardization 시행 및 fit_intercept=True : "+str(scores13.mean()))
scores14 = cross_val_score(model_1_std1, X_train1_std, y_train1, cv=5)
print("Standardization 시행 및 fit_intercept=False : "+str(scores14.mean()))
scores15 = cross_val_score(model_1_minmax, X_train1_minmax, y_train1, cv=5)
print("Min-max scaling 시행 및 fit_intercept=True : "+str(scores15.mean()))
scores16 = cross_val_score(model_1_minmax1, X_train1_minmax, y_train1, cv=5)
print("Min-max scaling 시행 및 fit_intercept=False : "+str(scores16.mean()))

feature scaling 미시행 및 fit_intercept=True : 0.7072131075342746
feature scaling 미시행 및 fit_intercept=False : 0.7072131075342625
Standardization 시행 및 fit_intercept=True : 0.7070071882614553
Standardization 시행 및 fit_intercept=False : 0.3264729515251247
Min-max scaling 시행 및 fit_intercept=True : 0.7070966675747187
Min-max scaling 시행 및 fit_intercept=False : 0.7072131075342816


In [79]:
# 학습/평가 데이터 6:4 비율 모형 cross-validation 시행 후 예측력 계산

scores21 = cross_val_score(model_2, X_train2, y_train2, cv=5)
print("feature scaling 미시행 및 fit_intercept=True : "+str(scores21.mean()))
scores22 = cross_val_score(model1_2, X_train2, y_train2, cv=5)
print("feature scaling 미시행 및 fit_intercept=False : "+str(scores22.mean()))
scores23 = cross_val_score(model_2_std, X_train2_std, y_train2, cv=5)
print("Standardization 시행 및 fit_intercept=True : "+str(scores23.mean()))
scores24 = cross_val_score(model_2_std1, X_train2_std, y_train2, cv=5)
print("Standardization 시행 및 fit_intercept=False : "+str(scores24.mean()))
scores25 = cross_val_score(model_2_minmax, X_train2_minmax, y_train2, cv=5)
print("Min-max scaling 시행 및 fit_intercept=True : "+str(scores25.mean()))
scores26 = cross_val_score(model_2_minmax1, X_train2_minmax, y_train2, cv=5)
print("Min-max scaling 시행 및 fit_intercept=False : "+str(scores26.mean()))

feature scaling 미시행 및 fit_intercept=True : 0.6933286301797772
feature scaling 미시행 및 fit_intercept=False : 0.6933286301798043
Standardization 시행 및 fit_intercept=True : 0.693610041398331
Standardization 시행 및 fit_intercept=False : 0.28498589569378685
Min-max scaling 시행 및 fit_intercept=True : 0.6936996393816118
Min-max scaling 시행 및 fit_intercept=False : 0.6933286301797681


In [80]:
# cross-validation folds = 3

scores = cross_val_score(model, X_train, y_train, cv=3)
print(scores.mean())
scores1 = cross_val_score(model1, X_train, y_train, cv=3)
print(scores1.mean())
scores_std = cross_val_score(model_std, X_train_std, y_train, cv=3)
print(scores_std.mean())
scores_std1 = cross_val_score(model_std1, X_train_std, y_train, cv=3)
print(scores_std1.mean())
scores_minmax = cross_val_score(model_minmax, X_train_minmax, y_train, cv=3)
print(scores_minmax.mean())
scores_minmax1 = cross_val_score(model_minmax1, X_train_minmax, y_train, cv=3)
print(scores_minmax1.mean())

0.7311789923901482
0.7311789923902182
0.7310315955766425
0.3677112888111118
0.7311885069473871
0.731178992390173


In [81]:
# cross-validation folds = 5

scores = cross_val_score(model, X_train, y_train, cv=5)
print(scores.mean())
scores1 = cross_val_score(model1, X_train, y_train, cv=5)
print(scores1.mean())
scores_std = cross_val_score(model_std, X_train_std, y_train, cv=5)
print(scores_std.mean())
scores_std1 = cross_val_score(model_std1, X_train_std, y_train, cv=5)
print(scores_std1.mean())
scores_minmax = cross_val_score(model_minmax, X_train_minmax, y_train, cv=5)
print(scores_minmax.mean())
scores_minmax1 = cross_val_score(model_minmax1, X_train_minmax, y_train, cv=5)
print(scores_minmax1.mean())

0.7401615873641952
0.7401615873642048
0.7396854047467084
0.365497215251456
0.7401336776950262
0.7401615873641982


In [82]:
# cross-validation folds = 7

scores = cross_val_score(model, X_train, y_train, cv=7)
print(scores.mean())
scores1 = cross_val_score(model1, X_train, y_train, cv=7)
print(scores1.mean())
scores_std = cross_val_score(model_std, X_train_std, y_train, cv=7)
print(scores_std.mean())
scores_std1 = cross_val_score(model_std1, X_train_std, y_train, cv=7)
print(scores_std1.mean())
scores_minmax = cross_val_score(model_minmax, X_train_minmax, y_train, cv=7)
print(scores_minmax.mean())
scores_minmax1 = cross_val_score(model_minmax1, X_train_minmax, y_train, cv=7)
print(scores_minmax1.mean())

0.7286521246228747
0.7286521246228361
0.7285633583126341
0.35604862944497345
0.7285209345316659
0.7286521246228489


In [103]:
model.coef_

array([ 3.96459902e+03,  1.37229774e+05,  1.61003539e+02,  2.20716498e+02,
       -6.47559426e+04,  1.85002748e+02, -4.81776717e+04,  1.98515865e+05,
       -2.43798753e+05,  9.34605593e+04,  8.18853946e+04,  3.39076489e+03,
        1.59999499e+05, -2.45275658e+05, -3.89477328e+04,  4.59167897e+04,
       -3.37164864e+05, -2.55326310e+05, -5.73656754e+04,  9.75571517e+04,
        2.53779034e+05,  3.00657872e+05,  3.87366713e+03, -1.29799315e+04])

In [104]:
model1.coef_

array([ 3.96459902e+03,  1.37229774e+05,  1.61003539e+02,  2.20716498e+02,
       -6.47559426e+04,  1.85002748e+02,  5.36376681e+07,  5.38843617e+07,
        5.34420471e+07,  5.37793064e+07,  5.37677312e+07,  5.36892366e+07,
        5.38458453e+07,  5.34405702e+07,  2.14353906e+07,  2.15202551e+07,
        2.11371735e+07,  2.12190120e+07,  2.14169727e+07,  2.15718955e+07,
        2.17281174e+07,  2.17749962e+07,  2.14782120e+07,  2.14613584e+07])

In [105]:
model_minmax.coef_

array([ 9.31680771e+05,  9.40023952e+05,  1.53053184e+07,  4.41344709e+06,
       -5.82803484e+05,  2.03503023e+03, -4.81776717e+04,  1.98515865e+05,
       -2.43798753e+05,  9.34605593e+04,  8.18853946e+04,  3.39076489e+03,
        1.59999499e+05, -2.45275658e+05, -3.89477328e+04,  4.59167897e+04,
       -3.37164864e+05, -2.55326310e+05, -5.73656754e+04,  9.75571517e+04,
        2.53779034e+05,  3.00657872e+05,  3.87366713e+03, -1.29799315e+04])

In [106]:
model_minmax1.coef_

array([ 9.31680771e+05,  9.40023952e+05,  1.53053184e+07,  4.41344709e+06,
       -5.82803484e+05,  2.03503023e+03, -3.93443238e+05, -1.46749701e+05,
       -5.89064320e+05, -2.51805007e+05, -2.63380172e+05, -3.41874802e+05,
       -1.85266068e+05, -5.90541225e+05, -1.77053960e+05, -9.21894370e+04,
       -4.75271091e+05, -3.93432537e+05, -1.95471902e+05, -4.05490750e+04,
        1.15672808e+05,  1.62551645e+05, -1.34232560e+05, -1.51086158e+05])